class LeagueTranslator {
  static String translate(String? raw) {
    if (raw == null || raw.trim().isEmpty) {
      return 'Turnamen Olahraga';
    }

    String text = raw.trim();

    // 1. Kamus Liga & Turnamen Khusus (Prioritas Tertinggi)
    final exactAndPrefixMap = <Pattern, String>{
      RegExp(r'Cúp Quốc Gia Việt Nam', caseSensitive: false): 'Piala Nasional Vietnam',
      RegExp(r'VĐQG Việt Nam|V\.League\s*1', caseSensitive: false): 'V.League 1 (Vietnam)',
      RegExp(r'Hạng Nhất Việt Nam|V\.League\s*2', caseSensitive: false): 'V.League 2 (Vietnam)',
      RegExp(r'Ngoại Hạng Anh|Premier League', caseSensitive: false): 'Premier League (Inggris)',
      RegExp(r'VĐQG Indonesia|Liga\s*1\s*Indonesia', caseSensitive: false): 'BRI Liga 1 Indonesia',
      RegExp(r'Hạng 2 Indonesia|Liga\s*2\s*Indonesia', caseSensitive: false): 'Liga 2 Indonesia',
      RegExp(r'Hạng 3 Indonesia|Liga\s*3\s*Indonesia', caseSensitive: false): 'Liga 3 Indonesia',
      RegExp(r'VĐQG Tây Ban Nha|La\s*Liga(?!\s*2)', caseSensitive: false): 'La Liga (Spanyol)',
      RegExp(r'Hạng 2 Tây Ban Nha|La\s*Liga\s*2|Segunda\s*División', caseSensitive: false): 'La Liga 2 (Spanyol)',
      RegExp(r'VĐQG Ý|Serie\s*A(?!\s*2)', caseSensitive: false): 'Serie A (Italia)',
      RegExp(r'Hạng 2 Ý|Serie\s*B', caseSensitive: false): 'Serie B (Italia)',
      RegExp(r'VĐQG Đức|Bundesliga(?!\s*2)', caseSensitive: false): 'Bundesliga (Jerman)',
      RegExp(r'Hạng 2 Đức|2\.\s*Bundesliga', caseSensitive: false): '2. Bundesliga (Jerman)',
      RegExp(r'VĐQG Pháp|Ligue\s*1', caseSensitive: false): 'Ligue 1 (Prancis)',
      RegExp(r'Hạng 2 Pháp|Ligue\s*2', caseSensitive: false): 'Ligue 2 (Prancis)',
      RegExp(r'VĐQG Hà Lan|Eredivisie', caseSensitive: false): 'Eredivisie (Belanda)',
      RegExp(r'VĐQG Bồ Đào Nha|Liga\s*Portugal|Primeira\s*Liga', caseSensitive: false): 'Liga Portugal',
      RegExp(r'VĐQG Saudi Arabia|VĐQG Ả Rập Xê Út|Saudi\s*Pro\s*League', caseSensitive: false): 'Saudi Pro League',
      RegExp(r'VĐQG Nhật Bản|J1\s*League', caseSensitive: false): 'J1 League (Jepang)',
      RegExp(r'Hạng 2 Nhật Bản|J2\s*League', caseSensitive: false): 'J2 League (Jepang)',
      RegExp(r'Hạng 3 Nhật Bản|J3\s*League', caseSensitive: false): 'J3 League (Jepang)',
      RegExp(r'Japan Football League|JFL', caseSensitive: false): 'Liga Sepak Bola Jepang (JFL)',
      RegExp(r'VĐQG Hàn Quốc|K\s*League\s*1', caseSensitive: false): 'K League 1 (Korea Selatan)',
      RegExp(r'Hạng 2 Hàn Quốc|K\s*League\s*2', caseSensitive: false): 'K League 2 (Korea Selatan)',
      RegExp(r'Hạng Nhất Ukraina', caseSensitive: false): 'Liga Utama Ukraina',
      RegExp(r'Hạng Nhất Anh|Championship', caseSensitive: false): 'Championship (Inggris)',
      RegExp(r'Hạng 2 Trung Quốc|China\s*League\s*One', caseSensitive: false): 'Liga 2 China',
      RegExp(r'Hạng 2 Romania', caseSensitive: false): 'Liga 2 Rumania',
      RegExp(r'Ngoại Hạng Darwin', caseSensitive: false): 'Liga Utama Darwin (Australia)',
      RegExp(r'Czech\s*3\s*liga', caseSensitive: false): 'Liga 3 Republik Ceko',
      RegExp(r'Bangladesh\s*Premier\s*League', caseSensitive: false): 'Liga Utama Bangladesh',
      RegExp(r'National Basketball League|NBL', caseSensitive: false): 'Liga Basket Nasional (NBL)',
      RegExp(r'Philippines University Athletic Association|UAAP', caseSensitive: false): 'Liga Universitas Filipina (UAAP)',
      RegExp(r'Turkish Basketball First League', caseSensitive: false): 'Liga Basket Divisi 1 Turki',
      RegExp(r'Vietnam VBA|VBA', caseSensitive: false): 'Liga Basket Vietnam (VBA)',
      RegExp(r'VTB United League Supercup', caseSensitive: false): 'Piala Super VTB United League',
      RegExp(r'Italy Super Cup', caseSensitive: false): 'Piala Super Italia',
      RegExp(r'Basketball Bundesliga', caseSensitive: false): 'Bundesliga Basket (Jerman)',
      RegExp(r'Spain Basketball Supercopa', caseSensitive: false): 'Piala Super Basket Spanyol',
      RegExp(r'Women National Basketball Association|WNBA', caseSensitive: false): 'Liga Basket Wanita Amerika (WNBA)',
      RegExp(r'Liga Nacional de Baloncesto Profesional|LNBP', caseSensitive: false): 'Liga Basket Profesional Meksiko (LNBP)',
      RegExp(r"Asian Games\s*-\s*Women'?s Basketball", caseSensitive: false): 'Asian Games - Bola Basket Putri',
      RegExp(r'Copa del Rey de Baloncesto', caseSensitive: false): 'Piala Raja Basket Spanyol',
      RegExp(r'WTA Seoul.*', caseSensitive: false): 'WTA Seoul (Tunggal Putri Korea Selatan)',
      RegExp(r'Davis Cup', caseSensitive: false): 'Piala Davis (Tenis)',
      RegExp(r'European Championships', caseSensitive: false): 'Kejuaraan Eropa',
      RegExp(r'LPL Regional Finals 2026', caseSensitive: false): 'Final Regional LPL 2026 (LoL)',
      RegExp(r'VCS Finals 2026', caseSensitive: false): 'Final VCS 2026 (LoL)',
      RegExp(r'Rift Legends Summer 2026', caseSensitive: false): 'Rift Legends Musim Panas 2026',
      RegExp(r'LEC Summer 2026', caseSensitive: false): 'LEC Musim Panas 2026 (LoL)',
      RegExp(r'LIT Summer 2026', caseSensitive: false): 'LIT Musim Panas 2026',
      RegExp(r'LCS Summer 2026', caseSensitive: false): 'LCS Musim Panas 2026 (LoL)',
      RegExp(r'PGL Wallachia Season 9', caseSensitive: false): 'PGL Wallachia Musim 9 (Dota 2)',
      RegExp(r'European Pro League Season 40', caseSensitive: false): 'Liga Pro Eropa Musim 40',
      RegExp(r'CCT 2026 Europe Series 9', caseSensitive: false): 'CCT 2026 Seri Eropa 9 (CS2)',
      RegExp(r'StarLadder StarSeries Season 22', caseSensitive: false): 'StarLadder StarSeries Musim 22 (CS2)',
      RegExp(r'NODWIN Clutch Series 12', caseSensitive: false): 'NODWIN Clutch Seri 12',
      RegExp(r'HyperX Retake Season 12', caseSensitive: false): 'HyperX Retake Musim 12',
      RegExp(r'CROSSFIRE Season 6', caseSensitive: false): 'CROSSFIRE Musim 6',
      RegExp(r'Cúp C1|Champions League|UEFA Champions League', caseSensitive: false): 'Liga Champions',
      RegExp(r'Cúp C2|Europa League|UEFA Europa League', caseSensitive: false): 'Liga Europa',
      RegExp(r'Cúp C3|Conference League|UEFA Conference League', caseSensitive: false): 'Liga Konferensi Eropa',
      RegExp(r'Cúp FA', caseSensitive: false): 'Piala FA (Inggris)',
      RegExp(r'Cúp Nhà Vua', caseSensitive: false): 'Copa del Rey (Spanyol)',
      RegExp(r'Cúp Quốc Gia', caseSensitive: false): 'Piala Nasional',
      RegExp(r'Cúp Liên Đoàn', caseSensitive: false): 'Piala Liga',
      RegExp(r'Siêu Cúp', caseSensitive: false): 'Piala Super',
      RegExp(r'Giao hữu quốc tế', caseSensitive: false): 'Laga Persahabatan Internasional',
      RegExp(r'Giao hữu CLB', caseSensitive: false): 'Laga Persahabatan Klub',
      RegExp(r'Giao hữu', caseSensitive: false): 'Laga Persahabatan',
      RegExp(r'Giải vô địch', caseSensitive: false): 'Kejuaraan',
      RegExp(r'Vòng loại World Cup', caseSensitive: false): 'Kualifikasi Piala Dunia',
      RegExp(r'Vòng loại Asian Cup', caseSensitive: false): 'Kualifikasi Piala Asia',
      RegExp(r'Vòng loại Euro', caseSensitive: false): 'Kualifikasi Euro',
      RegExp(r'Vòng loại', caseSensitive: false): 'Kualifikasi',
      RegExp(r'Bán kết', caseSensitive: false): 'Semifinal',
      RegExp(r'Chung kết', caseSensitive: false): 'Final',
      RegExp(r'Tứ kết', caseSensitive: false): 'Perempat Final',
      RegExp(r'Vòng Bảng', caseSensitive: false): 'Fase Grup',
      RegExp(r'Hạng 2', caseSensitive: false): 'Divisi 2',
      RegExp(r'Hạng 3', caseSensitive: false): 'Divisi 3',
      RegExp(r'Hạng 4', caseSensitive: false): 'Divisi 4',
      RegExp(r'Hạng Nhất', caseSensitive: false): 'Divisi Utama',
      RegExp(r'Ngoại Hạng', caseSensitive: false): 'Liga Utama',
      RegExp(r'VĐQG', caseSensitive: false): 'Liga Utama',
      RegExp(r'Cúp', caseSensitive: false): 'Piala',
    };

    exactAndPrefixMap.forEach((pattern, replacement) {
      text = text.replaceAll(pattern, replacement);
    });

    // 2. Kamus Kata dan Istilah Umum Olahraga
    final wordsMap = <Pattern, String>{
      RegExp(r'\bSeason\b', caseSensitive: false): 'Musim',
      RegExp(r'\bSeries\b', caseSensitive: false): 'Seri',
      RegExp(r'\bSummer\b', caseSensitive: false): 'Musim Panas',
      RegExp(r'\bSpring\b', caseSensitive: false): 'Musim Semi',
      RegExp(r'\bAutumn\b|\bFall\b', caseSensitive: false): 'Musim Gugur',
      RegExp(r'\bWinter\b', caseSensitive: false): 'Musim Dingin',
      RegExp(r'\bFinals\b', caseSensitive: false): 'Final',
      RegExp(r'\bSemifinals\b', caseSensitive: false): 'Semifinal',
      RegExp(r'\bQuarterfinals\b', caseSensitive: false): 'Perempat Final',
      RegExp(r'\bSingles\b', caseSensitive: false): 'Tunggal',
      RegExp(r'\bDoubles\b', caseSensitive: false): 'Ganda',
      RegExp(r'\bWomen\b|\bNữ\b', caseSensitive: false): 'Wanita',
      RegExp(r'\bMen\b|\bNam\b', caseSensitive: false): 'Pria',
      RegExp(r'\bTrẻ\b', caseSensitive: false): 'Muda',
      RegExp(r'\bCLB\s+', caseSensitive: false): 'Klub ',
      RegExp(r'\bĐông Nam Á\b', caseSensitive: false): 'Asia Tenggara',
      RegExp(r'\bChâu Á\b', caseSensitive: false): 'Asia',
      RegExp(r'\bChâu Âu\b', caseSensitive: false): 'Eropa',
      RegExp(r'\bChâu Mỹ\b', caseSensitive: false): 'Amerika',
      RegExp(r'\bChâu Phi\b', caseSensitive: false): 'Afrika',
      RegExp(r'\bBóng đá\b', caseSensitive: false): 'Sepak Bola',
      RegExp(r'\bBóng rổ\b', caseSensitive: false): 'Bola Basket',
      RegExp(r'\bBóng chuyền\b', caseSensitive: false): 'Bola Voli',
      RegExp(r'\bCầu lông\b', caseSensitive: false): 'Bulu Tangkis',
      RegExp(r'\bQuần vợt\b', caseSensitive: false): 'Tenis',
      RegExp(r'\bNhật Bản\b', caseSensitive: false): 'Jepang',
      RegExp(r'\bHàn Quốc\b', caseSensitive: false): 'Korea Selatan',
      RegExp(r'\bTriều Tiên\b', caseSensitive: false): 'Korea Utara',
      RegExp(r'\bTrung Quốc\b', caseSensitive: false): 'China',
      RegExp(r'\bĐài Loan\b', caseSensitive: false): 'Taiwan',
      RegExp(r'\bHồng Kông\b', caseSensitive: false): 'Hong Kong',
      RegExp(r'\bTây Ban Nha\b', caseSensitive: false): 'Spanyol',
      RegExp(r'\bÝ\b'): 'Italia',
      RegExp(r'\bĐức\b', caseSensitive: false): 'Jerman',
      RegExp(r'\bPháp\b', caseSensitive: false): 'Prancis',
      RegExp(r'\bAnh\b'): 'Inggris',
      RegExp(r'\bHà Lan\b', caseSensitive: false): 'Belanda',
      RegExp(r'\bBồ Đào Nha\b', caseSensitive: false): 'Portugal',
      RegExp(r'\bThái Lan\b', caseSensitive: false): 'Thailand',
      RegExp(r'\bMỹ\b|\bHoa Kỳ\b', caseSensitive: false): 'Amerika Serikat',
      RegExp(r'\bÚc\b', caseSensitive: false): 'Australia',
      RegExp(r'\bThụy Sĩ\b', caseSensitive: false): 'Swiss',
      RegExp(r'\bThụy Điển\b', caseSensitive: false): 'Swedia',
      RegExp(r'\bThổ Nhĩ Kỳ\b', caseSensitive: false): 'Turki',
      RegExp(r'\bNga\b'): 'Rusia',
      RegExp(r'\bHy Lạp\b', caseSensitive: false): 'Yunani',
      RegExp(r'\bẢ Rập Xê Út\b|\bẢ Rập Saudi\b', caseSensitive: false): 'Arab Saudi',
      RegExp(r'\bIndonesia\b', caseSensitive: false): 'Indonesia',
      RegExp(r'\bViệt Nam\b', caseSensitive: false): 'Vietnam',
    };

    wordsMap.forEach((pattern, replacement) {
      text = text.replaceAll(pattern, replacement);
    });

    return text.replaceAll(RegExp(r'\s+'), ' ').trim();
  }
}
